application: daily-prayer
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: prayer.app

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"
